# Generated by Django 4.2.4 on 2023-11-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('ver_menu_admin', 'Permite ver menu de admin'), ('crear_jugadores_desde_archivo', 'Permite cargar archivo de jugadores'), ('generar_fixtur', 'Permite generar el fixture de partidos'), ('eliminar_jugadores_de_forma_masiva', 'Permite eliminar todos los jugadores cargados'))},
        ),
    ]
