# Generated by Django 4.2.4 on 2023-08-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('escudo', models.FileField(blank=True, null=True, upload_to='equipo_files/escudos/')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('salario', models.FloatField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellido'],
            },
        ),
    ]
