# Generated by Django 4.2.4 on 2023-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_equipo_escudo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['apellido'], 'permissions': (('ver_salario', 'Permite a los dirigentes ver el salario'),), 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_fundado',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='pais',
            field=models.IntegerField(choices=[(1, 'URUGUAY'), (2, 'ARGENTINA')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='fin_contrado',
            field=models.DateField(null=True),
        ),
    ]
