# Generated by Django 4.2.4 on 2023-09-05 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_alter_jugador_options_equipo_fecha_fundado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fin_contrado',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
