# Generated by Django 4.2.4 on 2023-09-07 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0004_alter_jugador_fin_contrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.AddField(
            model_name='jugador',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='fichado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='pie',
            field=models.IntegerField(choices=[(1, 'DERECHO'), (2, 'IZQUIERDO')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='valor_mercado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fundado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='pais',
            field=models.IntegerField(choices=[(1, 'URUGUAY'), (2, 'ARGENTINA')], default=1),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fin_contrado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
