# Generated by Django 4.2.4 on 2023-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_remove_jugador_edad_jugador_altura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='fin_contrado',
            new_name='fin_contrato',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='salario',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='valor_mercado',
            field=models.FloatField(default=0),
        ),
    ]
