# Generated by Django 4.2.4 on 2023-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0006_rename_fin_contrado_jugador_fin_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
