# Generated by Django 4.2.4 on 2023-09-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0007_jugador_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.IntegerField(choices=[(1, 'ARQUERO'), (2, 'LATERAL IZQUIERDO'), (3, 'LATERAL DERECHO'), (2, 'LATERAL IZQUIERDO'), (4, 'MEDIOCAMPO'), (5, 'VOLANTE IZQUIERDO'), (6, 'VOLANTE DERECHA'), (7, 'DELANTERO'), (8, 'DEFENSA CENTRAL')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EquipoTrofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trofeo', models.IntegerField(choices=[(1, 'CAMPEONATO URUGUAYO'), (3, 'COPA LIBERTADORES'), (2, 'INTERMEDIO'), (4, 'COPA INTERCONTINENTAL')])),
                ('cantidad', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'Copas ganadas',
                'ordering': ['trofeo'],
            },
        ),
    ]
