# Generated by Django 4.2.4 on 2023-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0008_alter_jugador_posicion_equipotrofeo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipotrofeo',
            options={'ordering': ['trofeo'], 'verbose_name_plural': 'trofeo'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.IntegerField(choices=[(1, 'ARQUERO'), (2, 'LATERAL IZQUIERDO'), (3, 'LATERAL DERECHO'), (2, 'LATERAL IZQUIERDO'), (4, 'MEDIOCAMPO'), (5, 'VOLANTE IZQUIERDO'), (6, 'VOLANTE DERECHA'), (7, 'DELANTERO'), (8, 'DEFENSA CENTRAL'), (8, 'SIN DEFINIR')], default=8),
        ),
    ]
