# Generated by Django 4.2.4 on 2023-09-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0009_alter_equipotrofeo_options_alter_jugador_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='pais',
            field=models.IntegerField(choices=[(1, 'URUGUAY'), (2, 'ARGENTINA'), (3, 'CHILE')], default=1),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.IntegerField(choices=[(1, 'ARQUERO'), (2, 'LATERAL IZQUIERDO'), (3, 'LATERAL DERECHO'), (2, 'LATERAL IZQUIERDO'), (4, 'MEDIOCAMPO'), (5, 'VOLANTE IZQUIERDO'), (6, 'VOLANTE DERECHA'), (7, 'DELANTERO'), (8, 'DEFENSA CENTRAL'), (9, 'SIN DEFINIR')], default=9),
        ),
    ]
