# Generated by Django 4.2.4 on 2023-09-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0010_alter_equipo_pais_alter_jugador_posicion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipotrofeo',
            unique_together={('equipo', 'trofeo')},
        ),
    ]
