# Generated by Django 4.2.4 on 2023-09-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0011_alter_equipotrofeo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo'),
        ),
    ]
