# Generated by Django 4.2.4 on 2023-09-17 01:17

import conf.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0012_alter_jugador_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='altura',
            field=models.FloatField(blank=True, null=True, validators=[conf.validators.CustomValidators.valor_no_negativo]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='salario',
            field=models.FloatField(default=0, validators=[conf.validators.CustomValidators.valor_no_negativo]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='valor_mercado',
            field=models.FloatField(default=0, validators=[conf.validators.CustomValidators.valor_no_negativo]),
        ),
    ]
