# Generated by Django 4.2.4 on 2023-09-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0013_alter_jugador_altura_alter_jugador_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
