# Generated by Django 4.2.4 on 2023-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0014_equipo_historia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['nombre_completo'], 'permissions': (('ver_salario', 'Permite a los dirigentes ver el salario'),), 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='apellido',
            new_name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
    ]
