# Generated by Django 4.2.4 on 2023-10-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0015_alter_jugador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.FileField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
