# Generated by Django 4.2.4 on 2023-09-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_tokenactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenactivacion',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
