# Generated by Django 4.2.4 on 2023-09-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_equipo_escudo'),
        ('usuario', '0003_tokenactivacion_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirigente',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hincha',
            name='equipos',
            field=models.ManyToManyField(to='equipo.equipo'),
        ),
    ]
