# Generated by Django 4.2.4 on 2023-09-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_dirigente_equipo_hincha_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='token',
        ),
    ]
