# Generated by Django 4.2.4 on 2023-10-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_persona_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='rol',
        ),
    ]
