# Generated by Django 4.2.4 on 2023-10-03 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0016_alter_equipo_escudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.jugador')),
            ],
            options={
                'verbose_name_plural': 'Goles',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='equipo.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='equipo.equipo')),
                ('jugadores_goles', models.ManyToManyField(related_name='goles_jugador', through='campeonato.Gol', to='equipo.jugador')),
            ],
            options={
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.AddField(
            model_name='gol',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.partido'),
        ),
    ]
