# Generated by Django 4.2.4 on 2023-10-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_partido_ya_jugado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'permissions': (('simular_partido', 'Le permite al usuario simular partido'),), 'verbose_name_plural': 'Partidos'},
        ),
    ]
