# Generated by Django 4.2.4 on 2023-12-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0017_alter_equipo_nombre_alter_equipotrofeo_trofeo_and_more'),
        ('campeonato', '0004_alter_gol_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.jugador'),
        ),
    ]
